### ISSUE TITLE
awesome-ocap += rust cap-std

### ISSUE THREAD

**Issue by dckc** [bytecodealliance/cap-std#117]
Yay! I'm really glad to see this work. It's been on my wish-list since 2012 https://github.com/dckc/rust/issues/2 . And again in https://www.madmode.com/2017/ocap-wish-list.html

I just added this to https://github.com/dckc/awesome-ocap#lib

see also https://github.com/bluejekyll/trust-dns/pull/71

This isn't so much an issue as just getting in touch. Feel free to close this issue. (I'll close it myself after a bit, otherwise.)

**Comment by sunfishcode** [comment]
Cool, thanks for getting in touch!

One of the motivators for cap-std is [WASI](https://github.com/WebAssembly/WASI/), the WebAssembly System Interface, which is capability-based. Scanning through the links you posted, I see a lot of common themes -- WASI and cap-std have a lot of ideas from Capsicum and CloudABI, and several pieces of WASI are derived from CloudABI.

cap-std aims to follow Rust's `std` APIs as closely as possible, except where needed for eliminating ambient authorities. It wasn't initially obvious that this is a good way to approach the broader design space, however so far it appears to be working out fairly well. I'd be interested in any thoughts you have about this approach or cap-std's API.

**Comment by dckc** [comment]
The approach looks fine in general. As to the details... here's hoping for time to take a closer look.

**Comment by sunfishcode** [comment]
Thanks for the encouragement!
