### ISSUE TITLE
Resolve .. for opened directories before touching the filesystem

### ISSUE THREAD

**Issue by myfreeweb** [bytecodealliance/cap-std#122]
This looks like the perfect library for the [Capsicum](https://www.freebsd.org/cgi/man.cgi?capsicum(4)) sandbox, I'm happy to see more capability stuff!
I've tried to run an example:

```diff
--- i/examples/std_fs_misc.rs
+++ w/examples/std_fs_misc.rs
@@ -33,6 +33,8 @@ fn touch(dir: &mut Dir, path: &Path) -> io::Result<()> {
 
 fn main() {
     let mut cwd = unsafe { Dir::open_ambient_dir(".") }.expect("!");
+    extern "C" { fn cap_enter(); }
+    unsafe { cap_enter(); }
 
     println!("`mkdir a`");
```

And it's mostly great, but accessing the symlink fails:

```
`cat a/c/b.txt`
write(1,"`cat a/c/b.txt`\n",16)                  = 16 (0x10)
openat(3,"a",O_RDONLY|O_NOFOLLOW|O_DIRECTORY|O_CLOEXEC,00) = 4 (0x4)
openat(4,"c",O_RDONLY|O_NOFOLLOW|O_DIRECTORY|O_CLOEXEC,00) = 5 (0x5)
openat(5,"b.txt",O_RDONLY|O_NOFOLLOW|O_CLOEXEC,00) ERR#31 'Too many links'
readlinkat(5,"b.txt","../b.txt",256)             = 8 (0x8)
faccessat(5,"..",X_OK,AT_EACCESS)                ERR#93 'Capabilities insufficient'
close(4)                                         = 0 (0x0)
close(5)                                         = 0 (0x0)
! Os { code: 93, kind: Other, message: "Capabilities insufficient" }
```

It would be really nice if the regular posix implementation could resolve the symlink between the opened components by itself, i.e. instead of trying to access `..` at the `a/c` directory's descriptor, it would walk back its own "chain" of descriptors to `a`. Then it would actually be perfect :)

**Comment by myfreeweb** [comment]
(or.. should being in a sandbox just turn the open-each-level-separately behavior off? `openat(3,"a/c/b.txt",O_RDONLY,0)` does work)

**Comment by sunfishcode** [comment]
cap-std always resolves `..` by itself, by just walking back its own chain of descriptors, just as you say. That `faccessat` call is just to check whether the process has filesystem permissions to search `c`, in this case, to emulate what an unsandboxed path lookup would do if `b` had `chmod a-x` set on it. However, we should be able to do this by testing for access to `.` instead of `..` here, which in theory should fix this.

Are you able to test whether #123 fixes the issue for you?

**Comment by myfreeweb** [comment]
Oh yeah, it does, thanks!

```
`cat a/c/b.txt`
write(1,"`cat a/c/b.txt`\n",16)                  = 16 (0x10)
openat(3,"a",O_RDONLY|O_NOFOLLOW|O_DIRECTORY|O_CLOEXEC,00) = 6 (0x6)
openat(6,"c",O_RDONLY|O_NOFOLLOW|O_DIRECTORY|O_CLOEXEC,00) = 7 (0x7)
openat(7,"b.txt",O_RDONLY|O_NOFOLLOW|O_CLOEXEC,00) ERR#31 'Too many links'
readlinkat(7,"b.txt","../b.txt",256)             = 8 (0x8)
faccessat(7,".",X_OK,AT_EACCESS)                 = 0 (0x0)
close(7)                                         = 0 (0x0)
openat(6,"b.txt",O_RDONLY|O_NOFOLLOW|O_CLOEXEC,00) = 7 (0x7)
close(6)                                         = 0 (0x0)
read(7,"hello",32)                               = 5 (0x5)
read(7,0xcc71d48b045,27)                         = 0 (0x0)
close(7)                                         = 0 (0x0)
> hello
```

**Comment by sunfishcode** [comment]
> (or.. should being in a sandbox just turn the open-each-level-separately behavior off?

Capsicum's sandbox has slightly different semantics than cap-std -- for example, in Capsicum's capability mode, all `..` paths are rejected, while cap-std allows `..` if it refers to a directory already on the path resolution stack. For the use cases I'm focused on right now, it's important to avoid subtle behavior differences like this where possible. But if anyone has use cases which might want this, please file an issue so we can talk about it.
