### ISSUE TITLE
`DirEntry` metadata `ino` field panicks on Windows

### ISSUE THREAD

**Issue by pchickey** [bytecodealliance/cap-std#142]
Inside the `Dir::entries` iterator, calling `dir_entry.metadata()?` succeeds, but the `.ino()` accessor panicks, only on windows, with a message that says:
```
`ino` depends on a Metadata constructed from an open `File`
```

**Comment by sunfishcode** [comment]
Fixed in 154874592e9f917b4d277a1e086277802e36f716 (for `DirEntry`) and 01a30284a94ec09b1277fbca31d9ad3a9e80f687 (for `Dir`).
