### ISSUE TITLE
Are Windows reserved file names handled properly by `Dir::open`?

### ISSUE THREAD

**Issue by vi** [bytecodealliance/cap-std#165]
Or would trying to `Dir::open(allowed_dir, "COM1")` lead to opening thing not intended by the giver of `allowed_dir`?

**Comment by sunfishcode** [comment]
Yes; part of the `Dir::open` implementation on Windows appends the `open` argument to the `Dir` absolute path, so this would turn into something like `C:\Users\Me\COM1`, which when opened returns error code 2, "The system cannot find the file specified".

**Comment by sunfishcode** [comment]
It turns out that Windows treates "NUL" and "CON" differently from the other special names like "COM1". I've now made cap-std explicitly disallow opening these strings in #170.
