### ISSUE TITLE
AmbientAuthority verus a 'static str

### ISSUE THREAD

**Issue by mozfreddyb** [bytecodealliance/cap-std#175]
(Hi, I've come here from @sunfishcode's cap-std announcement blog post. Please redirect me to a better place if this is not the best forum for a discussion around this).

In my experience when auditing source code or trying to maintain certain security guarantees, it has always been useful to be able to distinguish between an arbitrary string and a hardcoded string (`'static str`). The hardcoded string can be scrutinized more easily and ideally just once during a code-review, whereas a dynamic string is potentially dangerous.

I understand that cap-std is mostly about runtime guarantees for sandboxing and this notion might be orthogonal to the guarantees you'd like to uphold with AmbientAuthority,  (e.g., denote all interactions with the outside world).

But would it be relevant to this project to introduce the notion of dynamic versus hardcoded strings?

I guess one could build some sort of static analysis (a clippy check?) that can restrict functions to only accept a static lifetime or declare additional shim functions that require their parameters to be `'static str`, which internally just call into the existing functions.

**Comment by sunfishcode** [comment]
I've now created https://github.com/sunfishcode/ambient-authority/pull/1 to add a function that could be used by such a macro.

**Comment by sunfishcode** [comment]
I now have an experimental library which provides `open_ambient_file!("foo")` and similar macros: 

https://github.com/sunfishcode/open-ambient

**Comment by mozfreddyb** [comment]
That's awesome, thank you!

**Comment by sunfishcode** [comment]
open-ambient is now published on crates.io! To explore this further, please follow up on the [open-ambient repo](https://github.com/sunfishcode/open-ambient).
