### ISSUE TITLE
Exploring traits for capabilities

### ISSUE THREAD

**Issue by chrysn** [bytecodealliance/cap-std#177]
The present crate could be quite convenient a way to get some std-ish functionality into embedded systems that otherwise don't implement all of std (and may not even have a generic allocator, let alone a generic one).

## Usages

I see two cases where this would be useful:

* Embedded operating systems often provide some functionalities of std, but only conditionally (eg. RIOT's file system is fully optional), and with reduced functionality.

  If a generic library (say, SHA-1'ing a file) were implemented using trait-based cap-std, it might have a `fn checksum(impl cap_std::fs::File) -> Hash;`, and could be used with a File passed in from the embedded OS's file system.

* Using non-OS file systems.

  Some desktop environments that are not OSes in the Rust platform sense provide their own virtual file system; KDE's kio and Gnome's gvfs are prime examples. They offer transparent integration of network file systems as well as things like treating zip files as folders.

  These could provide their own implementations of the cap_std traits, and again allow the direct use of generic libraries with them.

(I initially thought that given this is written in a WASM ecosystem this'd also be useful to give, say, an in-browser WASM program access to a file system through WebDAV, but that can more easily be done by just configuring cap-std to do that internally, given it already has platform specific code for different OSes anyway).

## Trouble

Apart from being quite some work to do, two aspects are particularly tricky:

* Versioning. Unlike structs, traits can only compatibly grow provided methods.

  Possible solutions are "know the API well in advance" (ie. develop this on structs to he point where it's unlikely that much needs to be added), "just bump versions" (possibly with compatibility mechanisms that implement the old trait on the new implementations) and "seal the trait, provide a generic impl based on a for-implementers crate, bump for-implementers crate version more frequently".

* GATs. Each `impl Dir for X` needs its own DirEntry type, own File type et cetera. That may need some GATs if any of the types is not owned (but I didn't check all the API yet to see whether that applies here).

## Prior Art

The [embedded-hal](https://github.com/rust-embedded/embedded-hal) ecosystem does pretty much that to great success.

## Question

Would it be in scope of cap-std to explore traits covering the capabilites?

**Comment by sunfishcode** [comment]
For something like `fn checksum(impl cap_std::fs::File) -> Hash;`, what would you think about `fn checksum(impl std::io::Read) -> Hash;`? That way, it works on whatever kind of file you have, and it *also* works on many other things, like pipes, sockets, and in-memory buffers. And it's friendlier for embedded platforms and virtual filesystems that don't always have the full traditional POSIX file feature set or behavior.

`Read` is for streaming once through the content. For libraries that need random access, I'm working on a [`ReadAt`](https://docs.rs/io-arrays/0.3.0/io_arrays/trait.ReadAt.html) trait and related things in the [io-arrays](https://github.com/sunfishcode/io-arrays) crate.

These avoid many of the problems that arise when we try to push "files" too hard as the unifying concept. Versioning is still a concern (`Read` as it exists today may not be the last word on the subject), but it's a much narrower one if we don't have to cover the huge and irregular surface area of "files".

For reading directories, looking at this from the perspective of libraries, most libraries aren't File Managers, so what would you think about a hypothetical `impl Iterator<Item = LazyInput>`? `LazyInput` would be something with accessors for [media types](https://en.wikipedia.org/wiki/Media_type) etc., to help libraries decide if an item is something they want to read, and then a way to returns an `impl Read` or `impl ReadAt` to read it. This would also be friendlier to embedded systems, virtual filesystems, mocking libraries, etc., than requiring full POSIX-like directory semantics (which get pretty complex in ways that rarely matter).

**Comment by chrysn** [comment]
Checksumming was a bad example (as indeed it can be replaced with some
read-ish thing like the io-arrays you mentioned). A better example might
have been reading a directory into an HTML directory listing. (As I
implement a file server in RIOT, that's almost an actual use case, save
for the the ouput data format).

Media types, thumbnails etc. would be conceptually fitting but probably
better reside on a higher level than what std provides (and thus is in
scope for cap-std) -- and should manager to build on the std based
types. For the applications I have in mind (versioning, file servers,
data synchronization, firmware updates), the low-level features
available here would work fine.

I do get your points about POSIX-correctness (even though not all Rust
platforms are POSIX, so neither with std nor cap-std I'd expect precise
compliance); indeed many backends would not provide these.

So do I get your gist right that you'd rather see something trait-style
be built atop of cap_std with suitable abstractions in place, and with
cap-std serving as a base of a reference std-based implementation?

(That does sound feasible to me: I could probably port std-embedded-nal
over to cap_std::net. Just still means that nobody yet takes the hard
work of going through the same steps for file systems, and from your
comments I take it if you were to do that it'd come out right ;-) ).

**Comment by sunfishcode** [comment]
Interesting. I had not looked at embedded_nal in detail before, but it appears operations like [`connect`](https://docs.rs/embedded-nal/0.6.0/embedded_nal/trait.TcpClientStack.html#tymethod.connect) take a "stack" parameter. It looks like cap_std::net's `Pool` could map to that. That's cool.

cap-std is focused on being a library with a similar interface to std with specific concepts introduced. If you want to abstract over it, I think a layer on top makes sense. I don't have an opinion about whether traits or structs or some other mechanism is best here.

Higher-level filesystem-oriented abstractions aren't currently a priority for me, but I'd be happy to give input on a design. My main suggestion up front would be to do something similar to embeded-nal's "stack" and cap_std::fs's Dir and avoid the concept of a global filesystem namespace.

**Comment by sunfishcode** [comment]
Traits for filesystem APIs are an interesting idea, and it'd be cool if they had the property that `embedded_nal` has of having a "stack"-like parameter which would allow them to be implemented on top of cap-std. That said, this would be best explored at a separate layer, rather than within cap-std itself. Feel free to re-open if you have any other questions!
