### ISSUE TITLE
How to create a new directory and open it as `Dir`?

### ISSUE THREAD

**Issue by repi** [bytecodealliance/cap-std#182]
How would one create a new root directory with `cap-std::fs` (that doesn't exist on disk already) with ambient authority and get a `Dir` for it?

`Dir::open_ambient_dir` fails on opening directories that do not exist, and there is no `Dir::create_ambient_dir`, and you need to have a `Dir` in the first place to use `Dir::create_dir` or `Dir::create_dir_all`.

For now working around this by using `std::fs::create_dir_all` before using `Dir::open_ambient_dir` but would like to be able to get rid of that. 

Are we missing some functionality here in in cap-std or am I missing something obvious?

**Comment by sunfishcode** [comment]
You aren't missing anything; that's just something no one else has needed yet. But it should be straightforward to add.

**Comment by repi** [comment]
Thanks for confirming!

**Comment by sunfishcode** [comment]
#183 adds a `Dir::create_ambient_dir_all` function. It seems to be consistent with `std` to have it not return the `Dir`; instead, you can call `Dir::open_ambient_dir` to open the created directory as a `Dir`, which is no less efficient since OS directory creation APIs themselves don't return a handle. But if that's awkward, I'm open to other approaches.

**Comment by sunfishcode** [comment]
This is now released in version 0.18.0; the docs are [here](https://docs.rs/cap-std/0.18.1/cap_std/fs/struct.Dir.html#method.create_ambient_dir_all).

**Comment by repi** [comment]
Sweet. Been using it and works well. Also initially was thinking that it could be more ergonomic to have it open and return a `Dir` directly, but feels like then you need to have some flags about if it should create the directory if it doesn't exist or fail in such cases.  Current new function works well enough, thanks for adding it!
