### ISSUE TITLE
Add a way to disable arf-string behavior in `fs_utf8`

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/cap-std#186]
cap-std's `fs_utf8` module was originally built as part of an experiment with UTF-8 paths in WASI, and one of the questions was whether we could make it possible to access files with non-Unicode encodings while still giving applications valid UTF-8 strings. This led to an experiment known as [`arf-strings`](https://github.com/bytecodealliance/arf-strings), which is a scheme for losslessly encoding non-UTF-8 bytes within a UTF-8 filename. `arf-strings` are currently built into `fs_utf8`, so specially crafted UTF-8 strings can be used to create and manipulate non-UTF-8 filenames.

However, [at least some users](https://gist.github.com/repi/11f60bbb93447e344fb7e45798be294e) of `fs_utf8` will not likely want this behavior, so cap-std should have a way to disable it, and possibly should disable it by default to be less surprising.

@repi

**Comment by repi** [comment]
ah was wondering what the `arf-strings` really was about :) 

indeed sounds like a good fit for a feature flag that is not on by default. we error everywhere on non-UTF8 paths and don't need to support them.

**Comment by sunfishcode** [comment]
https://github.com/bytecodealliance/cap-std/pull/188 is a PR which fixes this using a cargo feature.

**Comment by sunfishcode** [comment]
#188 is now released in 0.20.0.
