### ISSUE TITLE
Request: cap-std::process::Command

### ISSUE THREAD

**Issue by gilescope** [bytecodealliance/cap-std#190]
Can I start a process that is constrained to only having access to within a Dir?

(I understand that not all OSes may enforce this restriction).

**Comment by sunfishcode** [comment]
cap-std itself doesn't provide this functionality, however you could combine it with a separate sandboxing system to spawn a process with only access to a specific directory, and then create a `Dir` within the process pointing to that directory.

**Comment by sunfishcode** [comment]
Closing, as I believe the question here is answered. That kind of sandboxing is out of scope for cap-std, though cap-std could work within that sandbox. If anyone is interested in building this, or has questions, feel free to file new issues.
