### ISSUE TITLE
Looking forward to a 1.0 release

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/cap-std#192]
cap-std's coverage of std's fs, net, and time APIs is roughly as complete as it can be, and has been fairly stable for some time now. The one upcoming breaking change I'm aware of is that once the I/O safety features in std are stabilized, cap-std should use those and remove its `OwnsRaw` trait impls. That may be a good occasion to make a 1.0 semver release.

I could imagine potential future changes, such as changing the way the `Pool` type in `cap_std::net` works, but there's always 2.0 and beyond.

If there's anything that should go into a 1.0 release, please post about it!

**Comment by dckc** [comment]
nice to see this maturing!

The current `ambient_authority` approach looks pretty good. I wonder if there are better ways to use it in the examples: #206.

**Comment by sunfishcode** [comment]
Another future change will be when the I/O safety types `OwnedFd`, `BorrowedFd`, etc. are stabilized in std, and we can use them instead of using the io-lifetimes versions of them.

**Comment by sunfishcode** [comment]
Closing this out, as this is now tracked in #272.

Changes like changing `cap_std::net`'s `Pool` mechanism are still open for consideration, but are significant enough that we can think about those for a 2.0 release.
