### ISSUE TITLE
Cannot compile to `wasm32-wasi`

### ISSUE THREAD

**Issue by Cyborus04** [bytecodealliance/cap-std#195]
I was trying to make a crate for getting `cap_std::fs::Dir`s from wasi's preopened dirs, but hit a bit of a roadblock
It seems even when compiling to wasi, `cap-primitives` still tries to access `std::os::unix` 

```
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> cap-primitives\src\rsix\fs\copy_impl.rs:34:18
   |
34 |     use std::os::unix::fs::PermissionsExt;
   |                  ^^^^ could not find `unix` in `os`

+16 other errors
```

(on nightly)

**Comment by sunfishcode** [comment]
It appears cap-std's wasi port has fallen a bit behind. I'll work on that.

**Comment by sunfishcode** [comment]
This needs https://github.com/rust-lang/rust/pull/90835.
