### ISSUE TITLE
from sync to async Dir.

### ISSUE THREAD

**Issue by ranfdev** [bytecodealliance/cap-std#201]
Maybe I'm missing something, but I can't find a way to convert a sync Dir obtained with `cap_directories` to an async Dir compatible with cap_async_std.
The only solution at the moment seems to use the conversion Dir -> std::fs::File + ambient_authority-> async Dir.
It would be nicer to convert a Dir directly, without using ambient_authority.

**Comment by sunfishcode** [comment]
A shorter route is `Dir` -> `OwnedFd` -> `async Dir`, using `into_fd` and `from_fd`, from the `IntoFd` and `FromFd` trait implementations, respectively. That doesn't require an `AmbientAuthority`.

That said, thinking about it here, I wonder if it should, for the same reason that going through `File` does. Or perhaps going through a `File` shouldn't need it. I'll need to think about this more.

Either way though, the `into_fd` and `owned_fd` should work today, and an async version of cap-directories would also be a reasonable path here. The only reason an async cap-directories doesn't already exist is just that I didn't have a use case for it yet.

**Comment by ranfdev** [comment]
> I wonder if it [into_fd, from_fd] should [require AmbientAuthority], for the same reason that going through File does.

I don't think so. A file descriptor is already a capability. It may have been obtained by another process: the program shouldn't have to worry about its provenance. 

I would say the same thing goes for an owned `File`. Opening a file should certainly require `AmbientAuthority`, but once a file has been opened, it's just a wrapper around an `fd`.

Also, currently the method `Dir::from_std_file` requires `AmbientAuthority`, while I can bypass the requirement by doing: `Dir::from_fd(file.into_fd())`

**Comment by sunfishcode** [comment]
Yeah, that makes sense. The `from_std` functions were written before the [clippy config](https://github.com/sunfishcode/ambient-authority/blob/main/clippy.toml) was possible, and the thought was that a `std::fs::File` (as opposed to a `cap_std::fs::File`) indicated that the code may have constructed it with `std::fs::File::open`. However, I think those use cases are now better off using the clippy config to catch that. I've now filed #202 to remove the `AmbientAuthority` arguments from the `from_std` functions.

**Comment by sunfishcode** [comment]
If anyone would find an async version of cap-directories useful, please comment about it here, or in a new issue!

Closing this issue, as the current answer is `into_fd()` + `from_fd()`.
