### ISSUE TITLE
reduce scope of ambient_authority in examples?

### ISSUE THREAD

**Issue by dckc** [bytecodealliance/cap-std#206]
The `ambient_authority` function is in scope for the whole file:

https://github.com/bytecodealliance/cap-std/blob/c936cbb518a2e070571d4bff1cdc85aaf7d5608f/examples/std_fs_misc.rs#L4

Is there some way to leave it out of scope of everything but the main function? I should re-read how rust modules work.

Maybe main() would only call `open_ambient_dir` and then pass `cwd` to a function that does the rest?

**Comment by sunfishcode** [comment]
Closing; see discussion in #207.
