### ISSUE TITLE
Add `read_link_contents()` API?

### ISSUE THREAD

**Issue by cgwalters** [bytecodealliance/cap-std#251]
See https://github.com/coreos/rpm-ostree/pull/3771

Basically we have a use case where we want a `read_link()` that does escape checking for the link name, but not the link target.  (The current process is not going to follow the link target, so this is safe)

If you agree with this need I'm happy to do a PR to add those APIs here.

**Comment by sunfishcode** [comment]
Yeah, this makes sense to me.

In the code, it's an explicit check, so it should be straightforward to make a version that doesn't do this: https://github.com/bytecodealliance/cap-std/blob/main/cap-primitives/src/fs/read_link.rs#L24

**Comment by sunfishcode** [comment]
This is now fixed in #252.
