### ISSUE TITLE
Planning for a 0.26 release

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/cap-std#275]
The 1.0 release is [blocked](https://github.com/bytecodealliance/cap-std/issues/272#issuecomment-1224948992), but [users are](https://github.com/bytecodealliance/wasmtime/issues/4936) encountering https://github.com/bytecodealliance/cap-std/issues/270 now. We have a 0.26-patch2 prerelease with the fix, but I think it now makes sense to do a regular 0.26 release, to get the fix out, even though it will be another semver bump before 1.0.

The [0.26 branch](https://github.com/bytecodealliance/cap-std/tree/0.26) has the needed patches already, so I'm expecting to just do the 0.26 release from there.

**Comment by sunfishcode** [comment]
0.26.0 is now released.

**Comment by pinkforest** [comment]
We are using wasi-common: https://github.com/lunatic-solutions/lunatic/issues/136 but it doesn't have point release

I ended up wandering into std :hole: :rabbit2: first: https://github.com/rust-lang/rust/issues/102260

Is it possible to get a point release in wasi-common that gets cap-std 0.26 ?
```
│   │   │   ├── wasi-common v0.40.0
│   │   │   │   ├── cap-rand v0.25.2
│   │   │   │   ├── cap-std v0.25.2
│   │   │   │   │   ├── cap-primitives v0.25.2
```
