### ISSUE TITLE
1.0.16 had a breaking-change upgrading fs-set-times dependency

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/cap-std#324]
In https://github.com/bytecodealliance/cap-std/pull/321 the `cap-primitives` crate updated its dependency on `fs-set-times` from 0.19.x to 0.20.x, but the `fs-set-times` types are part of the public API of `cap-primitives` via the [`from_std`](https://docs.rs/cap-primitives/latest/cap_primitives/fs/enum.SystemTimeSpec.html#method.from_std) and `into_std` methods, meaning that upgrading a major version of a dependency is a breaking change on behalf of the `cap-primitives` crate.

This is causing [downstream issues](https://github.com/bytecodealliance/wasmtime/issues/6674#issuecomment-1614469046) where Wasmtime 10.0.1 no longer compiles with crates.io, for example.

**Comment by sunfishcode** [comment]
Confirmed; cap-std 1.0.16 had a breaking change. I've now yanked that version, and the original reported issue in https://github.com/bytecodealliance/wasmtime/issues/6674 is now fixed.
