### ISSUE TITLE
Question: can `cap-rand` and `rand` deduplicate non-ambient authority code?

### ISSUE THREAD

**Issue by nathan-at-least** [bytecodealliance/cap-std#325]
I have just discovered the `cap-std` crates and I'm really excited about them!

My understanding of `rand` is that it's full of code that doesn't rely on ambient authority, then also includes some ambient authorities such as `rand::thread_rng`.

Would it work better for everyone if we could separate out the ambient authorities of `rand` in order to reuse everything else?

How much of `cap-rand` is duplicate code?

**Comment by sunfishcode** [comment]
cap-rand is a very thin wrapper around rand, so no rand implementation code is duplicated. The main thing it does is just add `AmbientAuthority` arguments to the constructors that utilize ambient authority.

**Comment by sunfishcode** [comment]
The original question here seems answered; please file a new issue if there are any further questions!
