### ISSUE TITLE
How does the stable-versioned `cap-rand` intend to handle breaking changes in `rand`?

### ISSUE THREAD

**Issue by 8573** [bytecodealliance/cap-std#335]
`cap-rand` is a ["very thin wrapper"](https://github.com/bytecodealliance/cap-std/issues/325#issuecomment-1678008250) around `rand`. `cap-rand` has a major version number greater than zero, indicating that it intends rarely to have breaking changes, yet `rand` does not and does make breaking changes. How does `cap-rand` intend to respond when `rand` makes breaking changes?

**Comment by sunfishcode** [comment]
A major number of 0 doesn't necessarily indicate that a crate makes frequent breaking changes. The `rand` crate has been at 0.8 for almost 3 years at this point, and judging by a quick glance at the tracking issue, rand 0.9 is still a ways out yet. So I don't believe there's a conflict here.
