### ISSUE TITLE
Stop implementing std's `MetadataExt`

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/cap-std#342]
Rust is looking to seal `std::os::unix::fs::MetadataExt`:

https://github.com/rust-lang/rust/pull/118916

As in https://github.com/bytecodealliance/cap-std/pull/271 (which was before cap-std 1.0), cap-std can switch to defining its own copies of these traits. And since cap-std seems to be the only crate in the ecosystem that is affected, it should probably do this, to unblock std evolution.

However, this is a semver-incompatible change, so it'll require bumping cap-std to 3.0.

@cgwalters, who I know is particularly impacted by semver bumps

**Comment by cgwalters** [comment]
Since the cap-std 1.0 :arrow_right: 2.0 bump I did https://github.com/ostreedev/ostree/pull/3027 fixes the most painful thing to bump from my PoV.   So don't let me stand in the way of any Rust improvements!
