### ISSUE TITLE
Is it possible to get the absolute "paths" out of directory or files?

### ISSUE THREAD

**Issue by coderedart** [bytecodealliance/cap-std#347]
I love using this crate, because this allows me to clearly check which functions are accessing which part of the filesystem. And i use this as a sandboxing measure for lua guest scripts. But there are times where i want to print the actual path on the host side:

1. logging/tracing
2. displaying to users: In GUI, you often want to tell users that you are loading config from X location or storing/downloading this file to Y location etc..
3. can't think of any at this moment, but there are probably some more usecases.

But, i can't seem to figure out how to actually get a path out of the File/Dir structs. idk if they even store the path inside them. 

I know this may be an anti-feature for this crate, but i wanted to ask anyway. Maybe it would be possible to store path inside those structs behind a feature gate :)?

**Comment by sunfishcode** [comment]
No, the File/Dir structs do not store the path inside them. And yeah, for their main use case, storing the full paths would be kind of outside the spirit of the library :smile:. And things also get tricky if files or directories are renamed while something is open. For your use case, would you be able to create a `struct { file: File, path: Path }` type, and use that wherever you'd use a `File`?

**Comment by coderedart** [comment]
I did store the path along with file struct for a while, but
1. i would be writing a parallel cap-fs api
2. crates like cap-dirs/cap-directories would become pointless (as they don't provide a path at all), and having to use `dirs` crate directly. 

I guess i will just store the paths for important enough folders  :sob:
